version: "3.8"

services:
  elastic-orders:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: elasticsearch-orders
    ports:
      - "127.0.0.1:9200:9200"
    environment:
      - discovery.type=single-node
    restart: unless-stopped
  order-search:
    container_name: order-search
    build:
      context: .
    ports:
      - "127.0.0.1:8084:8084"
    restart: unless-stopped